<?php

namespace Openclerk\Currencies;

use \Monolog\Logger;

/**
 * A "HashableCurrency" is a currency which can be generated by hashing some algorithm.
 * In the future this can be extended to currencies which have multiple hashing algorithms.
 *
 * @see HashAlgorithm
 */
interface HashableCurrency extends Currency {

  /**
   * Get the main algorithm used by this currency for hashing, as a
   * code from {@link HashAlgorithm#getCode()}.
   *
   * {@link HashableCurrency}s which share the same hash algorithm can be considered
   * similar and their hash rates can be manipulated together.
   */
  public function getAlgorithm();

}
